# Copyright (c) IBM Corporation.
# Copyright (c) Microsoft Corporation.
- name: USER_NAME
  value: ""
  description: User name of GitHub account
- name: CLIENT_ID
  value: ""
  description: Client ID for an Azure AD application registered in the **Partner Center**
- name: SECRET_VALUE
  value: ""
  description: Secret value of the Azure AD application registered in the **Partner Center**
- name: TENANT_ID
  value: ""
  description: Tenant ID of the Azure AD application registered in the **Partner Center**
## Optional parameters: if you want to use optional parameters, please uncomment the following lines
#- name: MSTEAMS_WEBHOOK
#  value: ""
#  description: [Optional] Web hook for Microsoft Teams channel
